server:
  port: 7000
---
spring:
 application:
    name: mc-config
 profiles:
    active: native
 cloud:
    config:
      server:
        native:
          search-locations: file:///Users/santhoshramachandran/workspsce/micr-services/mc-confg-svr/src/test/resources/config
    