server:
  port: 7000
---
spring:
 application:
    name: ms-config-srv
 profiles:
    active: native
 cloud:
    config:
      server:
        native:
          search-locations: file:///Users/santhoshramachandran/workspsce/micr-services/ms-config-srv-file/src/test/resources/config
## use classpath: to load file from the classpath     